learning_model:
  source: 'model_defs/multi_point_model_kornia.py'
  # 아키텍처 설정
  architecture:
    # FPD 아키텍처 사용 여부 (true: FPD 분류 기반 회귀, false: 기존 MLP)
    use_fpd_architecture: true
    # Kornia 특징 설정 (feature extractor에서 사용)
    features:
      image_size: [112, 112]
      grid_size: 7
      use_color_hist: true
      use_hsv: true
      use_gradient: true
      use_lbp: true
      use_gabor: true
      use_hardnet: true  # HardNet으로 대체하여 ONNX 호환성 개선
      use_hog: false      # HOG 비활성화 (성능 개선 필요)
  # 모델 저장 설정
  checkpointing:
    save_dir: '../model'
    save_best_only: false
    save_frequency: 10            # 에폭 단위
    save_file_name: 'multi_point_kornia'  # 모델 파일명 (fpd_all.pth, fpd_all_best.pth)
    
# 데이터
data:
  source_folder: "../data/learning"  # 학습 데이터 경로
  labels_file: "labels.txt"  # 레이블 파일명
  test_id_suffix: '1'
  validation_ratio: 0.2
  random_seed: 42
  max_train_images: 200  # 학습 이미지 수 제한 (0이면 모두 사용, 100이면 100개만 사용)

# 특징 추출 설정
features:
  image_size: [112, 112]
  grid_size: 7

# 학습 설정
training:
  batch_size: 512
  epochs: 1000000
  learning_rate: 0.001
  weight_decay: 0.01
  optimizer: 'adamw'  # adam, adamw, sgd
  gradient_clip: 5.0
  extract_features: true  # true면 특징을 미리 추출하여 메모리에 캐싱 (학습 속도 10-20배 향상)

  # 데이터 증강
  augmentation:
    enabled: false
    augment_count: 3  # 원본 데이터당 증강 샘플 수
    # 크롭 증강 설정
    crop:
      enabled: true
      min_ratio: 0.8  # 최소 크롭 비율 (80%)
      max_ratio: 1.0  # 최대 크롭 비율 (100%)
      max_shift: 0.15  # 최대 이동 비율 (15%)

  # 학습률 스케줄러
  scheduler:
    type: 'reduce_on_plateau'
    patience: 20
    factor: 0.3
    min_lr: 0.000001

  # Loss 설정
  loss:
    soft_label_sigma: 1.0      # Soft label Gaussian 분포의 표준편차
  
  # Early stopping
  early_stopping:
    patience: 999999999  # 사실상 비활성화
    min_delta: 0.00000001

  # 오차 분석 설정
  error_analysis:
    enabled: true               # 오차 분석 기능 활성화
    interval: 10                 # 오차 분석 실행 간격 (에폭 단위)
    save_raw_data: true         # 오차 원천 데이터 저장 여부
    results_dir: '../result'   # 오차 데이터 저장 디렉토리

# 로깅 설정
logging:
  log_dir: '../logs'
