data:
  normalize_input: true
  use_grayscale: true
  source_folder: "../data/learning"  # 학습 데이터 경로
  labels_file: "labels.txt"  # 레이블 파일명

# 데이터 분할
data_split:
  test_id_suffix: '1'
  validation_ratio: 0.2
  random_seed: 42
  max_train_images: 200  # 학습 이미지 수 제한 (0이면 모두 사용, 100이면 100개만 사용)

device:
  cuda_device: 0
  use_cuda: true
feature_extraction:
  grid_size: 7
  image_size:
  - 112
  - 112
  latent_features:
    enabled: true
    normalize: false
  opencv_features:
    edge:
      canny_high: 150
      canny_low: 50
    edge_features: true
    enabled: true
    features_per_patch: 21
    hsv_mean: true
    orb:
      nfeatures: 5
      nlevels: 3
      scale_factor: 1.2
    orb_features: true
    pixel_stats: true
    rgb_mean: true
  patch_size: 16
logging:
  debug_mode: false
  verbose: false
model:
  autoencoder_full_path: ../model/ae_16x16_best.pth
  autoencoder_path: ../model/ae_16x16_encoder.pth
  input_channels: 1
  latent_dim: 16
output:
  combine_features: false

# 학습 설정
training:
  batch_size: 32
  epochs: 1000000
  learning_rate: 0.001
  weight_decay: 0.01
  optimizer: 'adamw'  # adam, adamw, sgd
  gradient_clip: 5.0
  
  # 학습률 스케줄러
  scheduler:
    type: 'reduce_on_plateau'
    patience: 100
    factor: 0.3
    min_lr: 0.00001
  
  # Early stopping
  early_stopping:
    patience: 999999999  # 사실상 비활성화
    min_delta: 0.00000001
  
  # 데이터 증강
  augmentation:
    enabled: true
    augment_count: 3  # 원본 데이터당 증강 샘플 수
    noise_std: 0.01  # 특징 벡터에 추가할 노이즈 표준편차
    # 크롭 증강 설정
    crop:
      enabled: true
      min_ratio: 0.8  # 최소 크롭 비율 (80%)
      max_ratio: 1.0  # 최대 크롭 비율 (100%)
      max_shift: 0.15  # 최대 이동 비율 (15%)
    # 좌표 정규화 범위 설정
    coordinate_range:
      x_min_ratio: -1.0  # x_min = -width (-112)
      x_max_ratio: 2.0   # x_max = width * 2 (224)
      y_min_ratio: 0.0   # y_min = 0
      y_max_ratio: 2.0   # y_max = height * 2 (224)
  
  # Loss 설정
  loss:
    classification_weight: 0.7  # Classification loss 가중치
    regression_weight: 0.3     # Regression loss 가중치
    soft_label_sigma: 1.0      # Soft label Gaussian 분포의 표준편차

  # 오차 분석 설정
  error_analysis:
    enabled: true               # 오차 분석 기능 활성화
    interval: 10                 # 오차 분석 실행 간격 (에폭 단위)
    save_raw_data: true         # 오차 원천 데이터 저장 여부
    results_dir: '../results'   # 오차 데이터 저장 디렉토리

# 모델 저장 설정
checkpointing:
  save_dir: '../model'
  save_best_only: true
  save_frequency: 10  # 에폭 단위
  model_name_prefix: 'fpd_coordinate_regression'
  save_file_name: 'fpd_attention'  # 모델 파일명 (fpd_all.pth, fpd_all_best.pth)
  resume_from: 'auto'  # 'auto': 자동 탐색, null: 새로 시작, 경로: 해당 파일 사용

# 로깅 설정
logging:
  log_dir: '../logs'
  progress_interval: 10  # 콘솔 진행 상황 출력 간격
  detail_interval: 1000   # 상세 정보 출력 간격
  verbose: true
  save_training_curve: true
  save_csv: true
  debug_mode: false
