# RvC 및 고급 모델 설정 파일
# Hybrid, Dual Positional, RvC 모델 설정 포함
# (Baseline 모델은 기존 config.yml 사용)

# ========================================
# 1. Hybrid Model 설정 (섹션 6)
# ========================================
hybrid_model:
  model_type: 'hybrid'
  use_latent: true
  use_handcrafted: true
  encoder_path: '../model/ae_16x16_encoder.pth'
  encoder_frozen: true  # Encoder 가중치 고정

  # 차원 설정
  handcrafted_dim: 903
  latent_dim: 784  # 49 patches × 16 dim
  input_dim: 1687  # 903 + 784

  # Positional Embedding
  positional_embedding:
    enabled: true
    embedding_dim: 16
    grid_size: 7
    combination: 'add'  # 'add' or 'concat'

  # Fusion Network
  hidden_dims: [768, 512, 256]
  dropout_rates: [0.2, 0.15, 0.1]
  activation: 'relu'
  use_batch_norm: true
  weight_init: 'he_normal'

# ========================================
# 2. Dual Positional Model 설정 (선택적, 섹션 7)
# ========================================
dual_positional_model:
  model_type: 'dual_positional'
  encoder_path: '../model/ae_16x16_encoder.pth'
  encoder_frozen: true

  # Dual Positional Embeddings
  positional_embedding:
    handcrafted:
      enabled: true
      embedding_dim: 32
      features_per_patch: 18
      projection_dim: 32
    latent:
      enabled: true
      embedding_dim: 16

  # Feature dimensions
  hand_crafted_dim: 903
  latent_dim: 784
  input_dim: 1687

  # Fusion Network
  hidden_dims: [768, 512, 256]
  dropout_rates: [0.2, 0.15, 0.1]
  activation: 'relu'
  use_batch_norm: true

# ========================================
# 3. RvC Model 설정 (섹션 12)
# ========================================
rvc_model:
  model_type: 'rvc'

  # 좌표 범위 설정
  x_range: [-112, 224]  # -width ~ 2*width
  y_range: [0, 224]     # 0 ~ 2*height

  # 빈 설정
  num_x_bins: 168  # x축 클래스 수 (336픽셀 / 168빈 = 각 빈당 2픽셀)
  num_y_bins: 112  # y축 클래스 수 (224픽셀 / 112빈 = 각 빈당 2픽셀)

  # 빈 분할 전략
  bin_strategy: 'uniform'  # 'uniform', 'adaptive', 'quantile'
  adaptive_config:
    center_range: [-50, 150]  # 중심부 범위
    center_bins: 100          # 중심부 빈 개수
    outer_bins: 20           # 외곽 빈 개수

  # 손실 함수 설정
  loss_type: 'ce_with_soft'  # 'ce', 'ce_with_soft', 'ordinal'
  use_soft_labels: true
  soft_label_sigma: 2.0  # Gaussian soft label 표준편차
  ordinal_weight: 0.1    # 순서 관계 패널티 가중치

  # 추론 설정
  inference_method: 'weighted_average'  # 'argmax', 'weighted_average'
  temperature: 1.0  # Softmax temperature

  # 불확실성 예측
  predict_uncertainty: true
  uncertainty_threshold: 0.5

  # 모델 아키텍처
  architecture:
    input_dim: 903  # 또는 1687 (hybrid), 2355 (dual_pos)

    # 특징 추출 네트워크
    feature_network:
      hidden_dims: [768, 512, 256]
      dropout_rates: [0.2, 0.15, 0.1]
      activation: 'relu'
      use_batch_norm: true

    # 분류 헤드
    classifier_head:
      hidden_dim: 128
      dropout: 0.1

# ========================================
# 4. 공통 학습 설정
# ========================================
training:
  batch_size: 64
  epochs: 100000
  learning_rate: 0.001
  weight_decay: 0.01
  optimizer: 'adamw'

  # 스케줄러
  scheduler:
    type: 'reduce_on_plateau'
    patience: 10
    factor: 0.5
    min_lr: 0.00001

  # Early stopping
  early_stopping:
    patience: 1000
    min_delta: 0.0001
    monitor: 'val_loss'

  # 체크포인트
  save_interval: 10
  viz_interval: 10

  # 데이터 분할
  val_split: 0.2
  test_split: 0.1
  random_seed: 42

# ========================================
# 5. 평가 지표
# ========================================
metrics:
  # 회귀 지표
  pixel_mae: true
  euclidean_distance: true

  # 분류 지표 (RvC용)
  top_k_accuracy: [1, 3, 5]

  # 불확실성 지표
  calibration_error: true
  entropy_analysis: true

# ========================================
# 6. 데이터 설정
# ========================================
data:
  input_size: 112
  grid_size: 7
  patch_size: 16

  # 증강 설정
  augmentation:
    random_crop: true
    crop_scale: [0.8, 1.0]
    horizontal_flip: true
    flip_prob: 0.5
    color_jitter: false
    rotation: false

  # 경로 설정
  data_path: '../data/base/not-labeled'
  cache_path: '../data/cache'

# ========================================
# 7. 로깅 설정
# ========================================
logging:
  log_level: 'INFO'
  log_dir: '../logs'
  tensorboard: true
  wandb: false

# ========================================
# 8. 디바이스 설정
# ========================================
device:
  cuda: true
  device_id: 0
  num_workers: 4
  pin_memory: true